apiVersion: v2
name: elixir-app
description: A modern Elixir/Phoenix application Helm chart for Kubernetes
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - elixir
  - phoenix
  - ash-framework
  - liveview
  - distributed-erlang
  - observability
home: https://github.com/your-org/engineering-elixir-applications-v2
sources:
  - https://github.com/your-org/engineering-elixir-applications-v2
maintainers:
  - name: Engineering Team
    email: engineering@yourorg.com
    url: https://yourorg.com
annotations:
  category: Application Framework
  licenses: MIT
dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.0.19
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled