# PROMTAIL LOG SHIPPING CONFIGURATION
# Ships logs from all AI Self-Sustaining System components to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    # Parse JSON logs from Docker
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))/(?P<container_id>(?:[^|]*))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          container_id:
      - output:
          source: output

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\S+\s+\S+\s+\S+)\s+(?P<hostname>\S+)\s+(?P<service>\S+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)'
      - timestamp:
          format: Jan 2 15:04:05
          source: timestamp
      - labels:
          hostname:
          service:
          pid:

  # Application-specific logs
  - job_name: phoenix-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: phoenix-app
          __path__: /var/log/phoenix/*.log
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) \[(?P<level>\w+)\] (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05.000'
          source: timestamp
      - labels:
          level:

  # N8N workflow logs
  - job_name: n8n
    static_configs:
      - targets:
          - localhost
        labels:
          job: n8n
          __path__: /var/log/n8n/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: message
            workflow_id: workflowId
            execution_id: executionId
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          workflow_id:
          execution_id:

  # Agent coordination logs
  - job_name: agent-coordination
    static_configs:
      - targets:
          - localhost
        labels:
          job: agent-coordination
          __path__: /app/agent_coordination/*.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] (?P<level>\w+): (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05'
          source: timestamp
      - labels:
          level:

  # Prometheus logs
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost
        labels:
          job: prometheus
          __path__: /var/log/prometheus/*.log
    pipeline_stages:
      - regex:
          expression: 'level=(?P<level>\w+) ts=(?P<timestamp>\S+) caller=(?P<caller>\S+) msg="(?P<message>[^"]*)"'
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:
          caller:

  # Grafana logs
  - job_name: grafana
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          __path__: /var/log/grafana/*.log
    pipeline_stages:
      - regex:
          expression: 't=(?P<timestamp>\S+) lvl=(?P<level>\w+) msg="(?P<message>[^"]*)"'
      - timestamp:
          format: RFC3339
          source: timestamp
      - labels:
          level:

# Global configuration
global:
  scrape_timeout: 10s