# BEAMOPS v3 Alert Rules - Following Engineering Elixir Applications patterns
# Production-ready alerting for agent coordination system

apiVersion: 1
groups:
  - orgId: 1
    name: beamops_agent_coordination
    folder: beamops_alerts
    interval: 1m
    rules:
      # Critical: Agent coordination system failure
      - uid: beamops-001-agent-coordination-failure
        title: Agent Coordination System Failure
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: agents_active_count
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params: [1]
                    type: lt
              refId: C
              type: threshold
        noDataState: Alerting
        execErrState: Alerting
        for: 2m
        isPaused: false
        
      # Warning: Low coordination efficiency
      - uid: beamops-002-low-coordination-efficiency
        title: Low Agent Coordination Efficiency
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: coordination_efficiency_ratio
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params: [0.7]
                    type: lt
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        isPaused: false
        
      # Warning: High work failure rate
      - uid: beamops-003-high-work-failure-rate
        title: High Agent Work Failure Rate
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: rate(work_completion_rate[10m])
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params: [5.0]
                    type: lt
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 10m
        isPaused: false
        
      # Critical: System health degradation
      - uid: beamops-004-system-health-degradation
        title: System Health Score Degradation
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: system_health_score
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params: [80.0]
                    type: lt
              refId: C
              type: threshold
        noDataState: Alerting
        execErrState: Alerting
        for: 3m
        isPaused: false

  # BEAM VM Health Alerts
  - orgId: 1
    name: beamops_beam_health
    folder: beamops_alerts
    interval: 1m
    rules:
      # Critical: High memory usage
      - uid: beamops-005-high-memory-usage
        title: BEAM VM High Memory Usage
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: (beam_memory_total / beam_memory_system_limit) * 100
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params: [85.0]
                    type: gt
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        isPaused: false