version: '3.8'

services:
  # Jaeger all-in-one with optimized settings
  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC
      - "14268:14268"  # Jaeger OTLP HTTP
      - "6831:6831/udp"  # Jaeger thrift compact
      - "6832:6832/udp"  # Jaeger thrift binary
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - MEMORY_MAX_TRACES=100000
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:16686/"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - otel-bulletproof

  # OpenTelemetry Collector with production settings
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    command: ["--config=/etc/otel-collector-bulletproof.yaml"]
    volumes:
      - ./otel-collector-bulletproof.yaml:/etc/otel-collector-bulletproof.yaml:ro
      - /tmp:/tmp
    ports:
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "8888:8888"    # Prometheus metrics
      - "13133:13133"  # Health check
    depends_on:
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:13133/"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - otel-bulletproof

networks:
  otel-bulletproof:
    driver: bridge
