# in compose.yaml

version: "3.9"

services:
  db:
    image: postgres:15.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}
    secrets:
      - postgrespassword

  beamops_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
        max_attempts: 3
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./app:/app
      - /app/_build
      - /app/deps
      - ./agent_coordination:/app/agent_coordination:ro
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      PHX_HOST: "localhost"
      MIX_ENV: "dev"
      COORDINATION_DIR: "/app/agent_coordination"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
      OTEL_SERVICE_NAME: "beamops_v2"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=beamops_v2,service.version=2.0.0"
    ports:
      - 4000:4000
      - 9568:9568  # PromEx metrics endpoint
    depends_on:
      - db
      - prometheus
    secrets:
      - databaseurl
      - secretkeybase

  # Agent coordination service
  coordination:
    build:
      context: ./coordination
      dockerfile: Dockerfile
    volumes:
      - ./agent_coordination:/coordination
      - ./coordination/scripts:/scripts:ro
    environment:
      COORDINATION_DIR: "/coordination"
      TELEMETRY_FILE: "/coordination/telemetry_spans.jsonl"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
      OTEL_SERVICE_NAME: "beamops_coordination"
    depends_on:
      - alloy

  loki:
    image: grafana/loki:2.9.3
    configs:
      - source: loki
        target: /etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    deploy:
      mode: global
    configs:
      - source: promtail
        target: /etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana:9.5.15
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasource.yaml
    volumes:
      - grafana-storage:/var/lib/grafana

  alloy:
    image: grafana/alloy:v1.1.1
    configs:
      - source: alloy
        target: /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus

volumes:
  db_data:
  grafana-storage:
  prometheus-data:

configs:
  prometheus:
    file: ./instrumentation/prometheus/local.yaml
  alloy:
    file: ./instrumentation/alloy/${ALLOY_CONFIG-swarm}.alloy
  loki:
    file: ./instrumentation/loki/local.yaml
  promtail:
    file: ./instrumentation/promtail/${PROMTAIL_CONFIG-swarm}.yaml
  grafana_datasources:
    file: ./instrumentation/grafana/datasources/datasources.yaml

secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
  secretkeybase:
    file: ./secrets/.secretkeybase
  databaseurl:
    file: ./secrets/.databaseurl
